language: php

php:
  - '7.2'

services:
  - mysql

env:
  - SYMFONY_VERSION="4.2.*" DB=mysql

install:
  - composer install
  - cp .env.test .env
  - php bin/console doctrine:database:create
  - php bin/console make:migration
  - php bin/console doctrine:migrations:migrate --no-interaction
  - php bin/console doctrine:fixtures:load -n

script:
  - php bin/phpunit tests\