language: php

php:
  - '7.2'

services:
  - mysql

env:
  - SYMFONY_VERSION="4.2.*" DB=mysql

install:
  - composer install
  - cp .env.test .env
  - php bin/console doctrine:database:create --env=test
  - php bin/console make:migration
  - php bin/console doctrine:migrations:migrate
  - php bin/console doctrine:fixtures:load --purge-with-truncate

script:
  - php bin/phpunit tests\